[tool.poetry]
name = "apps"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
tracedump = {path = "../.."}
pandas = "1.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
